### ISSUE TITLE
Ryan Thrash of MODX

### ISSUE THREAD

**Issue by coffeepunk** [thechangelog/ping#290]
Seems like an interesting person doing a lot of open source work. Think he has one or two stories to tell and it would also be cool to hear the story of MODX, which for me seems to be a fairly unknown CMS, but with a small thriving community.

[Ryans linkedin](https://www.linkedin.com/in/ryanthrash)

[MODX website](http://modx.com/)

**Comment by jerodsanto** [comment]
Boy did this suggestion fly under the radar. Sorry @coffeepunk, I just never could get excited about it. Maybe because of how many CMS-like things are out there?

Just realizing you opened this almost 4 years ago! I almost feel like I need to invoke [email debt forgiveness day](https://emaildebtforgiveness.me) not to feel like a jerk on this one... (again, sorry)
