### ISSUE TITLE
Dude, This is Cool

### ISSUE THREAD

**Issue by ranbureand** [thechangelog/ping#331]
Open source authors and contributors need much more love from the community. Those who initiate and share their projects, as well as those who participate and collaborate to constantly improve them, merit a big thank-you.

[Dude, This is Cool](http://dudethisis.cool/ "Dude, This is Cool") is a space where you can thank the amazing dudes behind your favorite open source projects on GitHub.

**Comment by jerodsanto** [comment]
@ranbureand _cool_ idea. I love the spirit of it. However, I'm concerned about the use of the term _dude_, since it typically refers exclusively to men. Any chances you'd be willing to rename to something more generic? A couple ideas:

* Wow, this is cool
* Thanks, this is cool

Whattya think?

**Comment by alpacaaa** [comment]
@jerodsanto Co-author here, thanks for the feedback.

We were worried as well about the term dude, especially because none of us is a native english speaker, so we weren't really sure about how the term is perceived. However, citing [Wikipedia](http://en.wikipedia.org/wiki/Dude):

> The female equivalent [of “dude”] was “dudette” or “dudess”, but these have both fallen into disuse, and “dude” is now also used as a unisex term.

Our stand on the issue (from our [colophon](https://dudethisis.cool/colophon/#fn:dude)):

> We are for gender equality: please don’t start any war here… thanks!

We are well aware that the issue of gender discrimination has been brought out a lot, especially here on Github. We think it's very important to address it and raise awareness in the dev community. That being said, I don't think a change of our project name is in scope, there's really no malice or prejudice behind what we're doing.

We'd love to be featured in The Changelog, but if this turns out to be a show stopper, we're totally cool with that and we understand your concerns. Would appreciate any further thoughts you guys might want to share.

**Comment by jerodsanto** [comment]
@alpacaaa I can only give my perspective as an English speaking male from the middle of America: the term is most often used in reference to men (and "dudette" is still in use on occasion).

I believe you 100% that there is no malice or prejudice coming from you and your team, which is why I suggest changing the language to ensure there is none implied.

I think the fact that you have to address the issue somewhere on the website is evidence enough that there are probably better options out there. Most people won't make it to your colophon. They'll judge what you're up to right when they read the page title.

We're going to pass on featuring the project with its current name. Please hit us up if you consider a rename (or with future cool stuff you all do!).

:beers:

**Comment by alpacaaa** [comment]
@jerodsanto Thank you so much for your insights, I agree 100% with what you're saying. I love our current name but we'll give it some more thought.

**Comment by jerodsanto** [comment]
Sounds good, we'll look forward to it. Thanks for sharing!

**Comment by ranbureand** [comment]
@jerodsanto it took some time but we have finally a new name for the project: [Yo, This is Cool](https://yothisis.cool/ "Yo, This is Cool")! Any chance you are going to reconsider this issue? :D

**Comment by jerodsanto** [comment]
@ranbureand well played! I think you all made the right decision and the name doesn't suffer from it at all. I'm queueing up a tweet in your direction and we'll also include this in the Projects section of this week's Changelog Weekly. :beers: :boom:

**Comment by alpacaaa** [comment]
@jerodsanto Totally cool, thanks!! :)

**Comment by ranbureand** [comment]
Many many thanks! ^_^
