### ISSUE TITLE
Interview Mike Pall, creator of LuaJIT

### ISSUE THREAD

**Issue by fritzo** [thechangelog/ping#412]
Not only did Mike Pall single-handedly put the JIT in [LuaJIT](http://luajit.org), he did so sustainably through over six years of [sponsored engineering projects](http://luajit.org/sponsors.html).

**Comment by alco** [comment]
It could be a great interview. The topic of JITs is hot in the tech world. Ruby is getting an [official JIT](https://medium.com/@k0kubun/ruby-2-6-jit-progress-and-future-84e0a830ecbf), there's talk about adding JIT to Erlang ([directly inspired](http://blog.erlang.org/My-OTP-21-Highlights/) by Mike Pall's work on LuaJIT). LuaJIT has been used for writing Nginx plugins for years [via OpenResty](https://github.com/openresty/lua-nginx-module).

Mike [moved on](https://www.freelists.org/post/luajit/Looking-for-new-LuaJIT-maintainers) from working on the project in 2015, though he can be seen leaving an occasional response on the mailing list. LuaJIT was forked and now lives on as [RaptorJIT](https://github.com/raptorjit/raptorjit).

I'd be nice to get Mike or Luke Gorrie (the maintainer of  RaptorJIT) on the show.

**Comment by alco** [comment]
It would be especially nice to hear what Mike learned while working on a **tracing JIT** for Lua. All major browsers also have tracing JITs for JavaScript (Chrome's V8, Safari's WebKit FTL, Firefox's Baseline JIT and IonMonkey),  For comparison, Ruby's newly released JIT still has a long way to go because it simply compiles a method when it's first called (as explained in [Heroku's blog post](https://blog.heroku.com/ruby-just-in-time-compilation#why-is-rails-slower)) which makes a lot of benchmarks show worse results compared to interpreting bytecode.

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
