### ISSUE TITLE
Main RSS feed has empty bodies

### ISSUE THREAD

**Issue by danmcclain** [thechangelog/ping#603]
I've noticed since the launch of the new site that the RSS feed just contains the title, with no summary or body

**Comment by jerodsanto** [comment]
@danmcclain good catch. 

We made that decision because it was one less thing between us and launch. [This commit](https://github.com/thechangelog/changelog.com/commit/e37eebe98a8ea8a7b47b69e868a2aba29943f57e) should put things back in order. 

Holler if you see anything else wrong in your feed reader. 💚
