### ISSUE TITLE
evolutionary kernel code

### ISSUE THREAD

**Issue by pdurbin** [thechangelog/ping#623]
At around 58:00 at https://changelog.com/rfc/11 @brendaneich says something about "evolutionary kernel code" but isn't sure of the source and hints that it may be from someone called Georgios Kontaxis (sp?) at Georgia State. Is there any more information about this? Thanks! Great episode!

**Comment by jerodsanto** [comment]
Hmm, not sure. @mikeal do you have any insight on this one?

**Comment by mikeal** [comment]
I can't remember the context of that comment offhand.

**Comment by jerodsanto** [comment]
@pdurbin I listened back and I think your interpretation is as good as it gets (aside from getting @brendaneich himself to answer). The closest thing I could find online is [A study of the Linux kernel evolution](http://dl.acm.org/citation.cfm?id=1131325), but that might not be it.

Closing this because ¯\_(ツ)_/¯

**Comment by pdurbin** [comment]
Ok, maybe some day I'll try to get an answer from @brendaneich himself. :smile:  Thanks for re-listening!
