### ISSUE TITLE
Post Changelog Weekly in the weekend for all time zones

### ISSUE THREAD

**Issue by pstavirs** [thechangelog/ping#652]
Developer based out of India here. The change in the posting time of the Weekly (happened a few months ago I guess) means that it arrives Sunday night India time and typically gets noticed/read only on Monday - not an ideal day considering its a work day. The mail just gets glanced through or sometimes not read at all depending on workload.

Requesting changing the posting time such that it arrives on Sat or worst case Sun morning for all time zones.

Keep up the good work!

**Comment by jerodsanto** [comment]
@pstavirs thanks for letting us know about your situation. _Of course_ we'd prefer if you could read it each and every week if possible. 😜 

It'd be awesome if we could get back on track where we're shipping Weekly on our Saturday morning instead of our Sunday morning. Currently we're so busy that it's unlikely in the short-term, but we'll take this in to consideration as we continue to expand, grow, and change.

Thanks again, it's always nice hearing from readers. 💚
