### ISSUE TITLE
I pinged but got no pong

### ISSUE THREAD

**Issue by alexhultman** [thechangelog/ping#680]
Two three weeks ago I sent a mail which got no reply. Is this normal or did you disregard it?

**Comment by jerodsanto** [comment]
Howdy @alexhultman! As you can imagine, we receive _a lot_ of email, so it's common for some things to slip through the cracks of our inboxes. 

In fact, because of this I have a Text Expander snippet that I use in response to emails like yours (I found it now) that basically says, "Please open this as an issue on our Ping repo". For one reason or another, I didn't get a response back to you. Sorry about that!

Speaking to the content of your email: No, we are not "hard Node.js fanatics", but we're going to pass on having you come on The Changelog. We've done a lot of JS-focused shows recently and we try to keep The Changelog's topics diverse. 

We have an [entire podcast focused on JavaScript now](https://changelog.com/jsparty), so we'll probably cover it less and less on The Changelog moving forward. You might make a good guest for JS Party down the road, but that show is currently a 3-person panel and we aren't doing guests at the moment.

That being said, you can totally participate with JS Party by [joining our community](https://changelog.com/community) and hanging out in the chat room during the [live recording](https://changelog.com/live). We hope to see you in there! 💚

**Comment by alexhultman** [comment]
Lol it was 'die hard' and it was not about JS (Node.js is a C++ SDK, not only a JS interpreter). I don't do JS but anyways, this was meant as a private mail so let me clarify how I wrote it (now that it is public): "Is it socially acceptable to invite yourself as a guest speaker? If so I would like to talk about Node.js performance, or rather the lack of it.". If I would talk about JS it would be from a completely different perspective and not the same old brainwashed nonsense as those people will talk about. Anyways, I won't come on then that's fine.
