### ISSUE TITLE
New newsletter style is clipped by Gmail

### ISSUE THREAD

**Issue by auspicacious** [thechangelog/ping#801]
Gmail automatically clips the display of emails larger than a certain limit -- I'm not sure how they calculate it. Your last newsletter (189) was clipped just after the "How do you spy on a program running in a container?" article. Although it's possible to see the full email by clicking on the "View entire message" link, this harms readability.

**Comment by jerodsanto** [comment]
Thanks for notifying us of this, @auspicacious! We'd love to avoid clipping if at all possible. This issue was a bit longer than most, and the new style definitely takes up more vertical space per news item.

We'll have to make a few adjustments, either by keeping our item count to ~20 (this one had 26), or by removing whitespace, or both!
