### ISSUE TITLE
Spinnaker Summit

### ISSUE THREAD

**Issue by mcgonagle** [thechangelog/ping#873]
Hello, my name is Thomas McGonagle, I met you both at a Github Universe party in San Francisco a few years back. We ended up going out together and going to the Puppet Party if that rings a bell. I hope all is well. 

 I was wondering if you had thought about attending/covering the Spinnaker Summit conference in San Diego on the weekend of 11/16-11/17. Perhaps my new employer Armory.io could make it happen. https://www.spinnakersummit.com

 I hope all is well. Please let me know if you have any questions or would like to brain storm.

**Comment by jerodsanto** [comment]
Thomas! It's awesome hearing from you. Adam and I were just talking about you while we were in Portland at OSCON a few weeks back.

Thanks for the invite on Spinnaker Summit. I wasn't aware of this project. This November might be tough to pull together since we already have some other travel booked this Fall and Adam has another kiddo on the way.

Happy to discuss further/alternate collaborations with ya. Email editors@changelog.com if you'd like, that goes to both Adam and I.
